
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Windows.Foundation.h>)
#include <winrt/Windows.Foundation.h>
#endif


namespace winrt::wakey::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct CustomDialogT : public ::winrt::wakey::implementation::CustomDialog_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename CustomDialogT::base_type;
        using base_type::base_type;
        using class_type = typename CustomDialogT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock Text()
        {
            return _Text;
        }
        void Text(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _Text = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon Icon()
        {
            return _Icon;
        }
        void Icon(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _Icon = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct CustomDialog_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _Text{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _Icon{nullptr};
    };
}

