
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Windows.Foundation.h>)
#include <winrt/Windows.Foundation.h>
#endif


namespace winrt::wakey::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::wakey::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid AppTitleBar()
        {
            return _AppTitleBar;
        }
        void AppTitleBar(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _AppTitleBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView navigationView()
        {
            return _navigationView;
        }
        void navigationView(::winrt::Microsoft::UI::Xaml::Controls::NavigationView value)
        {
            _navigationView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem General()
        {
            return _General;
        }
        void General(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _General = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem Settings()
        {
            return _Settings;
        }
        void Settings(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _Settings = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem Bluetooth()
        {
            return _Bluetooth;
        }
        void Bluetooth(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _Bluetooth = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem About()
        {
            return _About;
        }
        void About(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem value)
        {
            _About = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Frame contentFrame()
        {
            return _contentFrame;
        }
        void contentFrame(::winrt::Microsoft::UI::Xaml::Controls::Frame value)
        {
            _contentFrame = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Image TitleBarIcon()
        {
            return _TitleBarIcon;
        }
        void TitleBarIcon(::winrt::Microsoft::UI::Xaml::Controls::Image value)
        {
            _TitleBarIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock tbAppTitle()
        {
            return _tbAppTitle;
        }
        void tbAppTitle(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _tbAppTitle = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _AppTitleBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView _navigationView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _General{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _Settings{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _Bluetooth{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem _About{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Frame _contentFrame{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Image _TitleBarIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _tbAppTitle{nullptr};
    };
}

