
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Mntone.AngelUmbrella.Controls.h>)
#include <winrt/Mntone.AngelUmbrella.Controls.h>
#endif


namespace winrt::wakey::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct PageSettingsT : public ::winrt::wakey::implementation::PageSettings_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename PageSettingsT::base_type;
        using base_type::base_type;
        using class_type = typename PageSettingsT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock txtBattery()
        {
            return _txtBattery;
        }
        void txtBattery(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _txtBattery = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsExpander steBattery()
        {
            return _steBattery;
        }
        void steBattery(::winrt::Mntone::AngelUmbrella::Controls::SettingsExpander value)
        {
            _steBattery = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ListView listView()
        {
            return _listView;
        }
        void listView(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _listView = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel Bluetooth()
        {
            return _Bluetooth;
        }
        void Bluetooth(::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel value)
        {
            _Bluetooth = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel General()
        {
            return _General;
        }
        void General(::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel value)
        {
            _General = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcBatteryPower()
        {
            return _stcBatteryPower;
        }
        void stcBatteryPower(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcBatteryPower = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcBatterySaver()
        {
            return _stcBatterySaver;
        }
        void stcBatterySaver(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcBatterySaver = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoBatterySaver()
        {
            return _fntIcoBatterySaver;
        }
        void fntIcoBatterySaver(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoBatterySaver = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglBatterySaver()
        {
            return _tglBatterySaver;
        }
        void tglBatterySaver(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglBatterySaver = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoBatteryPower()
        {
            return _fntIcoBatteryPower;
        }
        void fntIcoBatteryPower(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoBatteryPower = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglBatteryPower()
        {
            return _tglBatteryPower;
        }
        void tglBatteryPower(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglBatteryPower = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcPowerMode()
        {
            return _stcPowerMode;
        }
        void stcPowerMode(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcPowerMode = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcPowerSettings()
        {
            return _stcPowerSettings;
        }
        void stcPowerSettings(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcPowerSettings = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoPowerSettings()
        {
            return _fntIcoPowerSettings;
        }
        void fntIcoPowerSettings(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoPowerSettings = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnPowerSettings()
        {
            return _btnPowerSettings;
        }
        void btnPowerSettings(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnPowerSettings = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoPowerMode()
        {
            return _fntIcoPowerMode;
        }
        void fntIcoPowerMode(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoPowerMode = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglPowerMode()
        {
            return _tglPowerMode;
        }
        void tglPowerMode(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglPowerMode = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcKeepScreenOn()
        {
            return _stcKeepScreenOn;
        }
        void stcKeepScreenOn(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcKeepScreenOn = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcTimeInterval()
        {
            return _stcTimeInterval;
        }
        void stcTimeInterval(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcTimeInterval = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox cboTimeInterval()
        {
            return _cboTimeInterval;
        }
        void cboTimeInterval(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _cboTimeInterval = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoKeepScreenOn()
        {
            return _fntIcoKeepScreenOn;
        }
        void fntIcoKeepScreenOn(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoKeepScreenOn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglKeepScreenOn()
        {
            return _tglKeepScreenOn;
        }
        void tglKeepScreenOn(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglKeepScreenOn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoKeepAwake()
        {
            return _fntIcoKeepAwake;
        }
        void fntIcoKeepAwake(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoKeepAwake = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglEnableWakey()
        {
            return _tglEnableWakey;
        }
        void tglEnableWakey(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglEnableWakey = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct PageSettings_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _txtBattery{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsExpander _steBattery{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ListView _listView{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel _Bluetooth{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel _General{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcBatteryPower{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcBatterySaver{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoBatterySaver{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglBatterySaver{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoBatteryPower{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglBatteryPower{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcPowerMode{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcPowerSettings{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoPowerSettings{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnPowerSettings{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoPowerMode{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglPowerMode{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcKeepScreenOn{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcTimeInterval{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _cboTimeInterval{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoKeepScreenOn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglKeepScreenOn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoKeepAwake{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglEnableWakey{nullptr};
    };
}

