
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Mntone.AngelUmbrella.Controls.h>)
#include <winrt/Mntone.AngelUmbrella.Controls.h>
#endif


namespace winrt::wakey::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct PageAboutT : public ::winrt::wakey::implementation::PageAbout_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename PageAboutT::base_type;
        using base_type::base_type;
        using class_type = typename PageAboutT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard ascUpdate()
        {
            return _ascUpdate;
        }
        void ascUpdate(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _ascUpdate = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard ascRate()
        {
            return _ascRate;
        }
        void ascRate(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _ascRate = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard ascPro()
        {
            return _ascPro;
        }
        void ascPro(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _ascPro = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing prgPurchase()
        {
            return _prgPurchase;
        }
        void prgPurchase(::winrt::Microsoft::UI::Xaml::Controls::ProgressRing value)
        {
            _prgPurchase = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnPro()
        {
            return _btnPro;
        }
        void btnPro(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnPro = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing prgRate()
        {
            return _prgRate;
        }
        void prgRate(::winrt::Microsoft::UI::Xaml::Controls::ProgressRing value)
        {
            _prgRate = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnRate()
        {
            return _btnRate;
        }
        void btnRate(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnRate = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing prgUpdate()
        {
            return _prgUpdate;
        }
        void prgUpdate(::winrt::Microsoft::UI::Xaml::Controls::ProgressRing value)
        {
            _prgUpdate = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnUpdate()
        {
            return _btnUpdate;
        }
        void btnUpdate(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnUpdate = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock txtAppDesc()
        {
            return _txtAppDesc;
        }
        void txtAppDesc(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _txtAppDesc = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton lnkHomePage()
        {
            return _lnkHomePage;
        }
        void lnkHomePage(::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton value)
        {
            _lnkHomePage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton lnkEmail()
        {
            return _lnkEmail;
        }
        void lnkEmail(::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton value)
        {
            _lnkEmail = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct PageAbout_obj1_Bindings;

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _ascUpdate{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _ascRate{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _ascPro{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing _prgPurchase{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnPro{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing _prgRate{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnRate{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing _prgUpdate{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnUpdate{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _txtAppDesc{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton _lnkHomePage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::HyperlinkButton _lnkEmail{nullptr};
    };
}

