
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Mntone.AngelUmbrella.Controls.h>)
#include <winrt/Mntone.AngelUmbrella.Controls.h>
#endif


namespace winrt::wakey::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct PageBluetoothT : public ::winrt::wakey::implementation::PageBluetooth_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename PageBluetoothT::base_type;
        using base_type::base_type;
        using class_type = typename PageBluetoothT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcHeader()
        {
            return _stcHeader;
        }
        void stcHeader(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcHeader = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::InfoBar infoBar()
        {
            return _infoBar;
        }
        void infoBar(::winrt::Microsoft::UI::Xaml::Controls::InfoBar value)
        {
            _infoBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ListView listView()
        {
            return _listView;
        }
        void listView(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _listView = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel Settings()
        {
            return _Settings;
        }
        void Settings(::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel value)
        {
            _Settings = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel General()
        {
            return _General;
        }
        void General(::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel value)
        {
            _General = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcDynamicLock()
        {
            return _stcDynamicLock;
        }
        void stcDynamicLock(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcDynamicLock = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcDynamicLockWin()
        {
            return _stcDynamicLockWin;
        }
        void stcDynamicLockWin(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcDynamicLockWin = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnDynamicLock()
        {
            return _btnDynamicLock;
        }
        void btnDynamicLock(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnDynamicLock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoDynamicLock()
        {
            return _fntIcoDynamicLock;
        }
        void fntIcoDynamicLock(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoDynamicLock = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglDynamicLock()
        {
            return _tglDynamicLock;
        }
        void tglDynamicLock(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglDynamicLock = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcDynamicLink()
        {
            return _stcDynamicLink;
        }
        void stcDynamicLink(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcDynamicLink = value;
        }

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard stcNewDevice()
        {
            return _stcNewDevice;
        }
        void stcNewDevice(::winrt::Mntone::AngelUmbrella::Controls::SettingsCard value)
        {
            _stcNewDevice = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button btnLinkBluetooth()
        {
            return _btnLinkBluetooth;
        }
        void btnLinkBluetooth(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _btnLinkBluetooth = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoDynamicLink()
        {
            return _fntIcoDynamicLink;
        }
        void fntIcoDynamicLink(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoDynamicLink = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing prgBluetooth()
        {
            return _prgBluetooth;
        }
        void prgBluetooth(::winrt::Microsoft::UI::Xaml::Controls::ProgressRing value)
        {
            _prgBluetooth = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox cboLink()
        {
            return _cboLink;
        }
        void cboLink(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _cboLink = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar prgBluetoothWin()
        {
            return _prgBluetoothWin;
        }
        void prgBluetoothWin(::winrt::Microsoft::UI::Xaml::Controls::ProgressBar value)
        {
            _prgBluetoothWin = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon fntIcoLink()
        {
            return _fntIcoLink;
        }
        void fntIcoLink(::winrt::Microsoft::UI::Xaml::Controls::FontIcon value)
        {
            _fntIcoLink = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch tglBluetooth()
        {
            return _tglBluetooth;
        }
        void tglBluetooth(::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch value)
        {
            _tglBluetooth = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct PageBluetooth_obj1_Bindings;

        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcHeader{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::InfoBar _infoBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ListView _listView{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel _Settings{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsPanel _General{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcDynamicLock{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcDynamicLockWin{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnDynamicLock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoDynamicLock{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglDynamicLock{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcDynamicLink{nullptr};
        ::winrt::Mntone::AngelUmbrella::Controls::SettingsCard _stcNewDevice{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _btnLinkBluetooth{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoDynamicLink{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressRing _prgBluetooth{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _cboLink{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ProgressBar _prgBluetoothWin{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::FontIcon _fntIcoLink{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ToggleSwitch _tglBluetooth{nullptr};
    };
}

